### ISSUE TITLE
Galaxy Tab S8 Ultra, Book Cover keyboard - touchpad axis inverted

### ISSUE THREAD

**Issue by markinhosmrk** [TrebleDroid/treble_experimentations#121]
Hi,

When using the touchpad in Book Cover keyboard, the touchpad axis are inverted (moving up/down moves left/right and vice versa, orientation seems to be portrait instead of landscape). Same issue happened in Android 13 builds but there using an .idc file with the following contents solved it, it does not work under Android 14:

/system/usr/idc/sec_touchpad_pogo.idc
```
touch.orientationAware = 0
touch.orientation = 0

```

I can see in dumpsys input and getevents that it is sec_touchpad_pogo device and it uses /dev/input/event15. When I apply the workaround that worked in Android 13 it shows the idc file being used in dumpsys. But apparently it is not applied, tried many different parameters there and no change at all.

```
Event Hub State:
  BuiltInKeyboardId: -2
  Devices:
    1: sec_touchpad_pogo
      Classes: TOUCH | TOUCH_MT | TOUCHPAD
      Path: /dev/input/event15
      Enabled: true
      Descriptor: 91b7b0aa27a986b5b229e149af0925f469502dfa
      Location:
      ControllerNumber: 0
      UniqueId:
      Identifier: bus=0x0000, vendor=0x0000, product=0x0000, version=0x0000, bluetoothAddress=<not set>
      KeyLayoutFile:
      KeyCharacterMapFile:
      ConfigurationFile:
      VideoDevice: <none>
      SysfsDevicePath: /sys/devices/platform/soc/soc:pogo_touchpad
      KeyState (pressed): <none>
      AbsState: ABS_X=0, ABS_Y=0, ABS_MT_SLOT=0, ABS_MT_TOUCH_MAJOR=0, ABS_MT_POSITION_X=0, ABS_MT_POSITION_Y=0, ABS_MT_TRACKING_ID=0

```

```
gts8uwifi:/system/usr/idc # getevent -ilt /dev/input/event15
add device 1: /dev/input/event15
  bus:      0000
  vendor    0000
  product   0000
  version   0000
  name:     "sec_touchpad_pogo"
  location: ""
  id:       ""
  version:  1.0.1
  events:
    KEY (0001): BTN_MOUSE             BTN_RIGHT             BTN_TOOL_FINGER       BTN_TOUCH
                BTN_TOOL_DOUBLETAP    BTN_TOOL_TRIPLETAP
    ABS (0003): ABS_X                 : value 0, min 0, max 1599, fuzz 0, flat 0, resolution 0
                ABS_Y                 : value 0, min 0, max 2559, fuzz 0, flat 0, resolution 0
                ABS_MT_SLOT           : value 0, min 0, max 2, fuzz 0, flat 0, resolution 0
                ABS_MT_TOUCH_MAJOR    : value 0, min 0, max 255, fuzz 0, flat 0, resolution 0
                ABS_MT_POSITION_X     : value 0, min 0, max 1599, fuzz 0, flat 0, resolution 0
                ABS_MT_POSITION_Y     : value 0, min 0, max 2559, fuzz 0, flat 0, resolution 0
                ABS_MT_TRACKING_ID    : value 0, min 0, max 65535, fuzz 0, flat 0, resolution 0
  input props:
    INPUT_PROP_POINTER
```

This is what I see using getevent -lt for the device.

```
Moving left/right

[     297.625773] EV_SYN       SYN_REPORT           00000000
[     297.642863] EV_ABS       ABS_MT_POSITION_Y    000002c1
[     297.642863] EV_SYN       SYN_REPORT           00000000
[     297.658765] EV_ABS       ABS_MT_POSITION_Y    000002c0
[     297.658765] EV_SYN       SYN_REPORT           00000000
[     297.683715] EV_ABS       ABS_MT_TOUCH_MAJOR   00000011
[     297.683715] EV_ABS       ABS_MT_POSITION_Y    000002bf

Moving up/down

[     332.485525] EV_SYN       SYN_REPORT           00000000
[     332.493136] EV_ABS       ABS_MT_POSITION_X    00000437
[     332.493136] EV_SYN       SYN_REPORT           00000000
[     332.501189] EV_ABS       ABS_MT_POSITION_X    00000438
[     332.501189] EV_SYN       SYN_REPORT           00000000
[     332.510128] EV_ABS       ABS_MT_POSITION_X    00000439
```

Any other way to invert axis for a touchpad? Please let me know if any additional info is needed.

Thanks,
Marcos

### Smartphone (please complete the following information):
 - Device: Galaxy Tab S8 Ultra + Book Cover keyboard/touchpad
 - Build Flavor: PixelOS_treble_arm64_bN-slim-14.0-20240512.img
